# References:
# bitnami/spark: https://raw.githubusercontent.com/bitnami/containers/main/bitnami/spark/docker-compose.yml
# apache/hadoop: https://hub.docker.com/r/apache/hadoop
# apache/hive: https://hive.apache.org/developement/quickstart/

x-hdfs-common:
  &hdfs-common
  


services:
  airflow:
    build: 
      context: ./containers/airflow
    env_file: ./containers/airflow/airflow.env
    volumes:
      - ./src/dags:/opt/airflow/dags
      - ./src/jobs:/opt/airflow/jobs
      - ./src/config:/opt/airflow/config
      - ./logs/airflow:/opt/airflow/logs
      - ./data:/data
    ports:
      - "8080:8080"

  spark-master:
    image: bitnami/spark:3.5
    env_file: ./containers/spark/spark-master.env
    ports:
      - '8088:8080'
    volumes:
      - ./data:/data
      - ./containers/spark/hive-site.xml:/opt/bitnami/spark/conf/hive-site.xml

  spark-worker:
    image: bitnami/spark:3.5
    env_file: ./containers/spark/spark-worker.env

  hdfs-namenode:
    image: apache/hadoop:3
    restart: unless-stopped
    env_file:
      - ./containers/hadoop-hive/hadoop-hive.env
    hostname: namenode
    command: ["hdfs", "namenode"]
    ports:
      - 9870:9870
    environment:
      - ENSURE_NAMENODE_DIR=/tmp/hadoop-hadoop/dfs/name
    healthcheck:
      test: ["CMD", "hdfs", "fsck", "/"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 10s
  
  hdfs-datanode:
    image: apache/hadoop:3
    restart: unless-stopped
    env_file:
      - ./containers/hadoop-hive/hadoop-hive.env
    command: ["hdfs", "datanode"]
  
  hive-server:
    image: apache/hive:3.1.3
    env_file:
      - ./containers/hadoop-hive/hadoop-hive.env
    volumes:
      - ./containers/hadoop-hive/conf:/hive-custom-conf
      - ./logs/hiveserver:/tmp/hive/
    environment:
      - HIVE_CUSTOM_CONF_DIR=/hive-custom-conf
      - SERVICE_NAME=hiveserver2
    ports:
      - 10000:10000
      - 10002:10002