# Customized from:
# - bitnami/spark: https://raw.githubusercontent.com/bitnami/containers/main/bitnami/spark/docker-compose.yml
# - apache/hadoop: https://hub.docker.com/r/apache/hadoop
  
x-spark-common:
  &spark-common
  image: bitnami/spark:3.5
  volumes:
    - ./containers/spark/requirements.txt:/requirements.txt
    - ./data:/data

x-hdfs-common:
  &hdfs-common
  image: apache/hadoop:3
  env_file:
    - ./containers/hdfs/hadoop.env

services:
  airflow:
    build: 
      context: ./containers/airflow
    env_file: ./containers/airflow/.env
    volumes:
      - ./containers/airflow/logs:/opt/airflow/logs
      - ./src/dags:/opt/airflow/dags
      - ./src/jobs:/opt/airflow/jobs
      - ./data:/data
    depends_on:
      hdfs-namenode:
        condition: service_healthy
    ports:
      - "8080:8080"

  spark-master:
    <<: *spark-common
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    ports:
      - '8088:8080'
  
  spark-worker:
    <<: *spark-common
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark

  hdfs-namenode:
    <<: *hdfs-common
    hostname: namenode
    command: ["hdfs", "namenode"]
    ports:
      - 9870:9870
    environment:
      ENSURE_NAMENODE_DIR: "/tmp/hadoop-root/dfs/name"
    healthcheck:
      test: ["CMD", "hdfs", "fsck", "/"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 10s
  
  hdfs-datanode:
    <<: *hdfs-common
    command: ["hdfs", "datanode"]